#!/usr/bin/env bash

if [ -f "access_token.txt" ]; then
	ACCESS_TOKEN=`cat access_token.txt`
	AUTHORIZATION_HEADER="Authorization: Bearer $ACCESS_TOKEN"
else
	AUTHORIZATION_HEADER=
fi

UUID=`cat uuid.txt`
printf "0: %.8x" 32 | xxd -r -g0 > input.bin
printf "0: %.8x" 32 | xxd -r -g0 >> input.bin
printf "0: %.8x" 32 | xxd -r -g0 >> input.bin
head -c 262144 /dev/urandom >> input.bin

REDIRECT=`curl -X GET -w %{redirect_url}  -H "$AUTHORIZATION_HEADER" \
  http://localhost:9080/datasets/$UUID/1/1/1/new/write?timeout=10000`

echo $REDIRECT

curl -X POST -c cookies.txt --data-binary "@input.bin" \
  -H "$AUTHORIZATION_HEADER" \
  -H "Content-Type: application/octet-stream" $REDIRECT'0/0/0/0/0/0/' 
  
curl -X POST -H "$AUTHORIZATION_HEADER" -b cookies.txt $REDIRECT'stop'

REDIRECT=`curl -X GET -H "$AUTHORIZATION_HEADER" -w %{redirect_url} \
  http://localhost:9080/datasets/$UUID/1/1/1/latest/read?timeout=10000`

echo $REDIRECT'0/0/0/0/0/0/'

curl -X GET -H "$AUTHORIZATION_HEADER" -b cookies.txt $REDIRECT'0/0/0/0/0/0/' --output output.bin

curl -X POST -H "$AUTHORIZATION_HEADER" -b cookies.txt $REDIRECT'stop'

diff input.bin output.bin
rm input.bin output.bin cookies.txt
