#!/usr/bin/env bash

docker run --rm -it --name cloudserver -v $(pwd)/data:/usr/src/app/localData -v $(pwd)/metadata:/usr/src/app/localMetadata -e ENDPOINT=localhost -p 8000:8000  -e REMOTE_MANAGEMENT_DISABLE=1  zenko/cloudserver