quarkus:
  http:
    port: 8080
    host: localhost
    read-timeout: 600s
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:./target/DataStore_DataRoot/h2;create=true
  hibernate-orm:
    log:
      sql: true
    database:
      generation: update
  shutdown:
    timeout: 1
